services:

  fastdatabase:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  fastapi:
    build: .
    image: fastzero
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - fastdatabase
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@fastdatabase:5432/app_db

volumes:
  pgdata:
