name: fastapi
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

  steps:
    name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.12"
