name: fastapi
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ALGORITHM: ${{secrets.ALGORITHM}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      ACCESSTOKENEXPIRE: ${{secrets.ACCESSTOKENEXPIRE}}

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v4

      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar o poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: poetry install --no-root

      - name: Executar testes
        run: poetry run task test
